### ISSUE TITLE
Problems on pygame.events.get() in continuous_carpole.py(line:109)

### ISSUE THREAD

**Issue by dornenkrone** [rperezdattari/COACH-gym#2]
dear professor:
when I run the code using my windows 10, i find the code blocked at continuous_carpole:109, After finding reference https://www.pygame.org/docs/ref/event.html
I find it hard to use pygame.events.get() outside of main thread, 
i'd be appreciate it if you could show me some inspiration

**Comment by rperezdattari** [comment]
Hello,

The code was tested in Ubuntu 16.04, so I have no experience running it on windows, I'm sorry.
